### ISSUE TITLE
uhhh, where is the RM skin?

### ISSUE THREAD

**Issue by amyy54** [ExcuseMi/rainmeter-overwatch#1]
I cant find the RM skin in the download. where is the file?

**Comment by ExcuseMi** [comment]
Just for others, if you go to https://github.com/ExcuseMi/rainmeter-overwatch/releases
It's in the rainmeter-overwatch-0.0.1.zip file.

**Comment by amyy54** [comment]
@ExcuseMi yeah I noticed it. that's why I closed the issue. Great work on the RM skin!
